# Changes here will be overwritten by Copier
_commit: 7a308a7
_src_path: https://github.com/browniebroke/pypackage-template
add_me_as_contributor: false
copyright_year: '2025'
documentation: true
email: bluetooth@koston.org
full_name: J. Nick Koston
github_username: bluetooth-devices
has_cli: false
initial_commit: true
is_django_package: false
open_source_license: MIT
package_name: aiousbwatcher
project_name: asyncio usb device watcher
project_short_description: Watch for USB devices to be plugged and unplugged
project_slug: aiousbwatcher
run_uv_sync: true
setup_github: true
setup_pre_commit: true

